"http://fluffynukeit.com/setting-up-vim-for-haskell/
set nocompatible | filetype indent plugin on | syn on

fun! SetupVAM()
  let c = get(g:, 'vim_addon_manager', {})
  let g:vim_addon_manager = c
  let c.plugin_root_dir = expand('$HOME', 1) . '/.vim/vim-addons'

  " Force your ~/.vim/after directory to be last in &rtp always:
  " let g:vim_addon_manager.rtp_list_hook = 'vam#ForceUsersAfterDirectoriesToBeLast'

  " most used options you may want to use:
  " let c.log_to_buf = 1
  let c.auto_install = 1
  let &rtp.=(empty(&rtp)?'':',').c.plugin_root_dir.'/vim-addon-manager'
  if !isdirectory(c.plugin_root_dir.'/vim-addon-manager/autoload')
    execute '!git clone --depth=1 git://github.com/MarcWeber/vim-addon-manager '
        \       shellescape(c.plugin_root_dir.'/vim-addon-manager', 1)
  endif

  " This provides the VAMActivate command, you could be passing plugin names, too
  call vam#ActivateAddons([ 'github:tpope/vim-unimpaired'
        \                 , 'github:tpope/vim-sensible'
        \                 , 'github:altercation/vim-colors-solarized'
        \                 , 'github:scrooloose/syntastic'
        \                 , 'github:raichoo/haskell-vim'
        \                 , 'github:eagletmt/neco-ghc'
        \                 , 'github:pbrisbin/vim-syntax-shakespeare'
        \                 , 'github:wting/rust.vim'
        \                 , 'github:MarcWeber/vim-addon-nix'
        \                 ], {})
"        \                 , 'github:Shougo/vimproc.vim'
"        \                 , 'github:eagletmt/ghcmod-vim'
endfun
call SetupVAM()


set encoding=utf8
set ffs=unix,dos,mac
set hlsearch
set incsearch
set confirm
set pastetoggle=<F11>
set number
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set mouse=a
set colorcolumn=80
set cmdheight=2
set ai
set si

let mapleader = ","
let g:mapleader = ","
set tm=2000

augroup haskell
  autocmd!
  autocmd FileType haskell map <silent> <leader><cr> :noh<cr>:GhcModTypeClear<cr>:SyntasticReset<cr>
  autocmd FileType haskell setlocal omnifunc=necoghc#omnifunc
  autocmd BufWritePost *.hs GhcModCheckAndLintAsync
augroup END

" SOLARIZED
syntax enable
set background=dark
colorscheme solarized

" SYNTASTIC
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
"let g:syntastic_debug = 3

" vim2hs
let g:haskell_enable_quantification = 1
let g:haskell_enable_recursivedo = 1
let g:haskell_enable_arrowsyntax = 1
let g:haskell_enable_pattern_synonyms = 1
let g:haskell_enable_typeroles = 1

let g:haskell_indent_if = 3
let g:haskell_indent_case = 5
let g:haskell_indent_let = 4
let g:haskell_indent_where = 6
let g:haskell_indent_do = 3
let g:haskell_indent_in = 1

" GhcMod
nmap <silent> <leader>t :GhcModType<cr>
nmap <silent> <leader>T :GhcModTypeInsert<cr>

